import React, { useState, useEffect, useRef } from 'react';
import { Brain, Send, Mic, MicOff, Volume2, VolumeX, Sparkles, AlertCircle } from 'lucide-react';
import API from '../../services/api.js';

const Chatbot = () => {
  const [messages, setMessages] = useState([
    { sender: 'ai', text: 'Hello! I am your CareerOS AI Assistant. I have context on your resume, coding streak, and roadmap. How can I help you prepare today?' }
  ]);
  const [input, setInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [isListening, setIsListening] = useState(false);
  const [speechEnabled, setSpeechEnabled] = useState(true);
  const messageEndRef = useRef(null);

  // Web Speech recognition variables
  const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
  const recognitionRef = useRef(null);

  useEffect(() => {
    if (SpeechRecognition) {
      const rec = new SpeechRecognition();
      rec.continuous = false;
      rec.interimResults = false;
      rec.lang = 'en-US';

      rec.onresult = (event) => {
        const text = event.results[0][0].transcript;
        setInput(text);
        setIsListening(false);
      };

      rec.onerror = (err) => {
        console.error('Speech recognition error:', err);
        setIsListening(false);
      };

      rec.onend = () => {
        setIsListening(false);
      };

      recognitionRef.current = rec;
    }
  }, [SpeechRecognition]);

  useEffect(() => {
    messageEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  const speakText = (text) => {
    if (!speechEnabled) return;
    try {
      window.speechSynthesis.cancel(); // Stop any current speech
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.rate = 1.0;
      utterance.pitch = 1.0;
      window.speechSynthesis.speak(utterance);
    } catch (e) {
      console.warn('Speech synthesis failed');
    }
  };

  const handleSend = async (textToSend) => {
    const text = textToSend || input;
    if (!text.trim()) return;

    const userMessage = { sender: 'user', text };
    setMessages((prev) => [...prev, userMessage]);
    setInput('');
    setLoading(true);

    try {
      // Direct post to email/chatbot or standard placement guidelines endpoint
      // We can use the cover letter or general prompt endpoint
      const { data } = await API.post('/ai/email-writer', {
        emailType: 'General Question',
        details: { question: text }
      });

      let reply = 'I am scanning my career models...';
      if (data.success && data.data) {
        // Strip the email subjects if generated by default endpoint
        reply = data.data.replace(/Subject:.*\n\n/, '');
      }

      setMessages((prev) => [...prev, { sender: 'ai', text: reply }]);
      speakText(reply);
    } catch (error) {
      setMessages((prev) => [...prev, { sender: 'ai', text: 'Sorry, I encountered an issue processing that query. Please try again.' }]);
    } finally {
      setLoading(false);
    }
  };

  const toggleListen = () => {
    if (!recognitionRef.current) {
      alert('Speech Recognition is not supported in this browser. Please use Google Chrome.');
      return;
    }
    if (isListening) {
      recognitionRef.current.stop();
      setIsListening(false);
    } else {
      setIsListening(true);
      recognitionRef.current.start();
    }
  };

  const handlePromptClick = (p) => {
    handleSend(p);
  };

  const suggestedPrompts = [
    'How do I improve my placement probability for Amazon?',
    'Write a referral email for a React Developer role.',
    'Explain the differences between MongoDB B-Tree and SQL structures.',
    'What should I highlight on my resume to fit Google criteria?'
  ];

  return (
    <div className="h-[calc(100vh-140px)] flex flex-col justify-between max-w-4xl mx-auto font-sans pb-4">
      {/* Top Header */}
      <div className="flex justify-between items-center border-b pb-4 mb-4">
        <div className="flex items-center gap-2">
          <Brain className="w-6 h-6 text-indigo-500" />
          <div>
            <h1 className="font-extrabold text-lg text-slate-850 dark:text-white">AI Placement Assistant</h1>
            <p className="text-[10px] text-slate-400">Ask career roadmaps, coding answers, resume details, and company prep guides</p>
          </div>
        </div>
        <button
          onClick={() => setSpeechEnabled(!speechEnabled)}
          className={`p-2 rounded-lg border transition-all ${
            speechEnabled
              ? 'border-indigo-500 bg-indigo-500/10 text-indigo-500'
              : 'border-slate-200 dark:border-slate-800 text-slate-450'
          }`}
          title="Toggle text-to-speech audio reader"
        >
          {speechEnabled ? <Volume2 className="w-4.5 h-4.5" /> : <VolumeX className="w-4.5 h-4.5" />}
        </button>
      </div>

      {/* Messages body */}
      <div className="flex-1 overflow-y-auto space-y-4 px-2 pr-4 min-h-0">
        {messages.map((m, idx) => (
          <div key={idx} className={`flex ${m.sender === 'user' ? 'justify-end' : 'justify-start'}`}>
            <div
              className={`max-w-xl rounded-2xl p-4 shadow-md text-xs leading-relaxed ${
                m.sender === 'user'
                  ? 'bg-indigo-650 text-white rounded-tr-none'
                  : 'bg-white dark:bg-slate-900 border border-slate-200/50 dark:border-slate-850 text-slate-750 dark:text-slate-205 rounded-tl-none'
              }`}
            >
              <div className="flex items-center gap-1.5 font-bold uppercase tracking-wider text-[9px] mb-1.5 opacity-70">
                {m.sender === 'ai' ? <Brain className="w-3 h-3 text-indigo-400" /> : null}
                <span>{m.sender === 'ai' ? 'CareerOS AI' : 'You'}</span>
              </div>
              <p className="whitespace-pre-line">{m.text}</p>
            </div>
          </div>
        ))}
        {loading && (
          <div className="flex justify-start">
            <div className="bg-white dark:bg-slate-900 border rounded-2xl rounded-tl-none p-4 text-xs max-w-sm flex items-center gap-3">
              <div className="w-2.5 h-2.5 bg-indigo-500 rounded-full animate-bounce" />
              <div className="w-2.5 h-2.5 bg-indigo-500 rounded-full animate-bounce [animation-delay:0.2s]" />
              <div className="w-2.5 h-2.5 bg-indigo-500 rounded-full animate-bounce [animation-delay:0.4s]" />
            </div>
          </div>
        )}
        <div ref={messageEndRef} />
      </div>

      {/* Suggested quickprompts */}
      {messages.length === 1 && (
        <div className="py-4 space-y-2">
          <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest px-1">Suggested Inquiries</p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
            {suggestedPrompts.map((p) => (
              <button
                key={p}
                onClick={() => handlePromptClick(p)}
                className="text-left bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 hover:border-indigo-500 hover:bg-indigo-500/[0.02] p-3 rounded-xl text-xs font-semibold text-slate-700 dark:text-slate-300 transition-all flex items-center gap-2"
              >
                <Sparkles className="w-3.5 h-3.5 text-indigo-500 shrink-0" />
                <span className="truncate">{p}</span>
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Input controls footer */}
      <div className="mt-4 flex gap-3 print:hidden">
        <button
          onClick={toggleListen}
          className={`p-3.5 rounded-xl border transition-all ${
            isListening
              ? 'bg-rose-500 text-white animate-pulse border-rose-500'
              : 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800 text-slate-500 hover:border-indigo-500 hover:text-indigo-500'
          }`}
          title={isListening ? 'Stop listening' : 'Dictate question via voice'}
        >
          {isListening ? <MicOff className="w-5 h-5" /> : <Mic className="w-5 h-5" />}
        </button>

        <input
          type="text"
          placeholder={isListening ? 'Speak now, AI is dictating...' : 'Ask your career planner question here...'}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => e.key === 'Enter' && handleSend()}
          className="flex-1 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 focus:border-indigo-500 rounded-xl px-4 text-xs text-slate-800 dark:text-slate-200 focus:outline-none"
        />

        <button
          onClick={() => handleSend()}
          className="bg-indigo-650 hover:bg-indigo-600 text-white p-3.5 rounded-xl shadow-lg hover:shadow-indigo-650/30 transition-all flex items-center justify-center shrink-0"
        >
          <Send className="w-5 h-5" />
        </button>
      </div>
    </div>
  );
};

export default Chatbot;
